### ISSUE TITLE
Why Not add a data persistence level into mongomock?

### ISSUE THREAD

**Issue by MacHu-GWU** [mongomock/mongomock#350]
Since mongomock use ``Document. _documents`` to hold the data, why can't add methods ``Database.load(path, **options)`` and ``Database.dump(path, **options)``?

**Comment by pcorpet** [comment]
Hi @MacHu-GWU , sorry for the long delay in the answer. I think we could probably add some persistence level in mongomock. However would we do that, I think we should not augment the Database API so that the database API stays as close as possible as the `pymongo` one.

So what we could have would be top module functions that would dump/load all indices and documents from a DB. Note that they could actually be in a separate package (no need to be inside mongomock) and work both on mock and real DB. See for instance this [answer on SO](https://stackoverflow.com/questions/24610484/pymongo-mongoengine-equivalent-of-mongodump). What do you think?

**Comment by nguyenhn-systran** [comment]
Hi @pcorpet , could you tell me whether MongoMock can now load data from a file ?
I'd like to see whether I can use MongoMock in the integration testing, using test data coming from the production dump. 
Thanks for information.

**Comment by pcorpet** [comment]
Sorry, there's no one-liner to do that however as explained above it should be easy to implement.

**Comment by fopina** [comment]
Adding persistence to mongomock would allow to use pymongo/mongoengine for local development, without actually running a mongo instance, :+1: on that :)

**Comment by wangwalton** [comment]
Hi ! I'm happy to make contributions on adding persistance to MongoMock. Can anyone provide some basic overview and pointers on getting started? @pcorpet
