### ISSUE TITLE
Using `bulk_write` with `ReplaceOne` raises `TypeError`

### ISSUE THREAD

**Issue by eliadl** [mongomock/mongomock#369]
```python
import mongomock  # 3.8.0
import pymongo    # 3.6.0

col = mongomock.MongoClient().db.collection
_id = col.insert_one({'k': 'v'})
col.bulk_write([pymongo.ReplaceOne(filter={'_id': _id},
                                   replacement={'k':'v2'})])
```
Raises this error:
```
mongomock/collection.pyc in bulk_write(self, operations)
   1656         bulk = BulkOperationBuilder(self)
   1657         for operation in operations:
-> 1658             operation._add_to_bulk(bulk)
   1659         return BulkWriteResult(bulk.execute(), True)
   1660 

pymongo/operations.pyc in _add_to_bulk(self, bulkobj)
    168         """Add this operation to the _Bulk instance `bulkobj`."""
    169         bulkobj.add_replace(self._filter, self._doc, self._upsert,
--> 170                             collation=self._collation)
    171 
    172     def __eq__(self, other):

TypeError: add_replace() got an unexpected keyword argument 'collation'
```

**Comment by vbrinnel** [comment]
Hi,

so I had the same pblm and fixed on my own. 
Later, I've realized that it was actually already fixed by mallikn in commit 447bc87.
The issue: when you pip3 install mongomock, you don't get the newest version.
This is what you need to do:

sudo pip3 uninstall mongomock

then:

sudo pip3 install git+https://github.com/mongomock/mongomock

mongomock is awesome to perform quick tests, hope this will help you.

Cheers,

**Comment by eliadl** [comment]
I'm on python 2, but I'll try that nevertheless. Thanks!

Why not release current fixes as 3.8.1?

**Comment by vbrinnel** [comment]
if you're on python2, just use pip rather that pip3 :)

If you pip install the package using git, you'll see that you'll get mongomock-3.8.1.dev30.
Why this update was not released yet might have to do with the fact that the present fix is more of a workaround than a real fix. I might be wrong but it seems to me that there is no real support for collation (https://docs.mongodb.com/manual/reference/collation/) on the mongomock side. Since the project I am working on does not require any special collation, the workaround works fine with me.

**Comment by eliadl** [comment]
Thanks.
I guess I'll leave it up to the maintainers whether to close this issue or not.
