### ISSUE TITLE
Testing a func with MongoClient defined

### ISSUE THREAD

**Issue by armudgal** [mongomock/mongomock#414]
HI,
It's a query rather than an actual issue so help would be appreciated.

I have a function that I want to test which is like
```
def connect(url):
        connection  = pymongo.MongoClient(url)
        db = connection.sampleDB
```

Now if I want to test this function, `MongoClient` is already defined, is there any way I can use `mongomock` to test this, given the fact that we only have the parameter `url` in our hands.

Please note this is a simple repro of my actual use case.

**Comment by pcorpet** [comment]
Hi @kilotaras,
Yes `mongomock` is there to help you: I suggest you use it in combination with the [mock library](https://docs.python.org/3/library/unittest.mock.html).

The idea is to replace the call to `pymongo.MongoClient` with your own function so that you can return a mongomock object.

In your test code:
```py
import unittest
from unittest import mock

import mongomock
import pymongo

class MyTest(unittest.TestCase):

   def test_something(self):
      mongo_client = mongomock.MongoClient()
      patcher = mock.patch(
        pymongo.__name__ + '.MongoClient', new=lambda url: mongo_client)
      patcher.start()
      self.addCleanup(patcher.stop)

      ... populate your db using mongo_client.sampleDB ...
      ... run your code ...
      ... check the changes on mongo_client.sampleDB ....
```

Unfortunately the actual DB content is stored within the mongomock.MongoClient object, therefore creating 2 clients with the same URL does **not** access the same data.

I hope that helps.

**Comment by armudgal** [comment]
Thankyou so much @pcorpet  This is exactly what I needed.

**Comment by armudgal** [comment]
Hi @pcorpet, sorry to reopen this but there were some changes in the simple repro

```
def connect():
        url = "mongodb://127.0.0.1:27017/"
        connection  = pymongo.MongoClient(url)
        db = connection.sampleDB
```
and to patch this I am simply using

`with patch(pymongo.__name__ + '.MongoClient', new_callable=mongomock.MongoClient):`

which is throwing an error `'MongoClient' object is not callable`, am I passing the wrong thing, if yes then what would be the right thing to pass?

**Comment by pcorpet** [comment]
This is because of how you use patch (because I misled you!). new_callable would actually call the function when trying to replace the function and so it will replace `pymongo.MongoClient` constructor with a `mongomock.MongoClient` object!

You should actually use:
```py
with patch(pymongo.__name__ + '.MongoClient', new=mongomock.MongoClient):
```
Unfortunately that prevents you from accessing the created clients (that contain the data), so you need to do the patching I was doing originally except that you replace `new_callable` by `new`. I'm going to edit my answer, but it was indeed me who got it wrong in the first place :-D

**Comment by armudgal** [comment]
HI @pcorpet ,Thanks a ton. I think I should have digged more into the difference between `new` and `new_callable`.
