### ISSUE TITLE
Please add Cursor.max_time_ms

### ISSUE THREAD

**Issue by ghost** [mongomock/mongomock#490]
Currently code using max_time_ms returns AttributeError: 'Cursor' object has no attribute 'max_time_ms'. I'm not sure what the implementation could be, though. By itself mongomock obviously never times out, but perhaps an easy way to patch it to do so could be included?

**Comment by pcorpet** [comment]
Thanks for reporting. It should at least throw a `NotImplemementedError` instead of an `AttributeError`. And as a first implementation we could just make it a no op for now as most of our operations run very quickly. If you need the usecase, please open a new issue to handle a timeout: it could be handy to test how your code behave on a timeout, however it's a significant change compared to the current mongomock philosophy so I'd rather have the discussion only if someone needs the feature.
