### ISSUE TITLE
Bad interaction between projection and sort

### ISSUE THREAD

**Issue by ghost** [mongomock/mongomock#491]
Sorting based on a field that is not included in the projection does not currently work, test case:

    def test__cursor_sort_projection(self):
        coll = self.db.create_collection('a')
        coll.insert_many([{'a': 1, 'b': 1}, {'a': 3, 'b': 3}, {'a': 2, 'b': 2}])

        self.assertEqual([1, 2, 3], [doc['b'] for doc in coll.find().sort({'a': 1})])
        self.assertEqual([1, 2, 3], [doc['b'] for doc in coll.find(projection=['b']).sort({'a': 1})])

**Comment by pcorpet** [comment]
Thanks for reporting. Indeed the Mongo specification explains that the sorting should be applied before the projection.

However your code is not compatible with pymongo, it seems that dicts cannot be used as a sorting key (I believe this is because dicts are not sorted in Python and here sorting matters).

I'll fix the bug you uncovered.

**Comment by ghost** [comment]
This test case started as a copy of the existing test__cursor_sort, does that also suffer from the same incompatibility?

I'm trying to use mongomock to run tests against a mongoengine-based application, so I'm doing a translation from that into 'raw' pymongo when writing test cases to trigger the problems I'm seeing.

**Comment by pcorpet** [comment]
Yes the other test suffered from the same incompatibility. Thanks for the translations :-) It really eases the debugging.
