### ISSUE TITLE
[Feature request] Add $facet aggregation operator pipeline

### ISSUE THREAD

**Issue by Joachim-Hease** [mongomock/mongomock#519]
Hello ! 

Thank for the awesome project. I am currently using it for one of my projects (Mongo 3.4 Mongomock 3.16.0) and I am facing the following issue:

```
NotImplementedError: Although '$facet' is a valid operator for the aggregation pipeline, it is currently not implemented in Mongomock.
``` 

Is it currently work in progress ?

I also use other operator. Have you a list of supported aggregate operator ?

**Comment by pcorpet** [comment]
Hi @Joachim-Hease, thanks for the praise and the interest.

Here's a list of missing features:
https://github.com/mongomock/mongomock/blob/develop/Missing_Features.rst

No it's not work in progress, mostly because this is a side project for all maintainers and we tend not to implement features is nobody is asking for them.

Feel free to send a pull request, otherwise if you're patient, one of us might take a look at it now that we know that at least one user would be happy to have the feature.
