### ISSUE TITLE
Add GridFS mock

### ISSUE THREAD

**Issue by toshitanian** [mongomock/mongomock#72]
I'm using this library to our production code, woking well for tests of pure mongo.  : )

However, I cannot test code using `gridfs.GridFS`.

So, I want  GridFS mock functions.

Best.
Kawasaki

**Comment by mmistroni** [comment]
Hi
 i need that feature too..... but i see it is closed?
could anyone clarify pls?
kind regards 
marco

**Comment by vmalloc** [comment]
@mmistroni you're seeing the referenced issue as closed (#111). This one is still open.

**Comment by drorasaf** [comment]
In order to support code without major changes, the Database and Collection objects must be able to disguise themselves as the respective pymongo object since there are checks inside pymongo.gridfs package about the type of the object.
Another requirement is to support partially the commands, since filemd5 is being used widely in gridfs

**Comment by c0d3d** [comment]
I made a PR for this a long time ago, and it never got merged. 
See: #311
If someone decides that it's worth merging, I can rebase.

**Comment by pcorpet** [comment]
#311 got it covered. Thanks @c0d3d
