### ISSUE TITLE
4.2.0.post1 issue: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by woutdenolf** [mongomock/mongomock#900]
Reproduce the issue:

```
python --version
Python 3.7.17

pip install --pre mongomock

python -c "import mongomock"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/denolf/.local/wdnbashutils/virtualenvs/pybox_wJkmoe/lib/python3.7/site-packages/mongomock/__init__.py", line 79, in <module>
    from mongomock.__version__ import __version__
  File "/home/denolf/.local/wdnbashutils/virtualenvs/pybox_wJkmoe/lib/python3.7/site-packages/mongomock/__version__.py", line 1, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```

`importlib.metadata` was introduced in python 3.8.

I might have missed it but I don't see any python version constraints. I believe v4.1.2 was working for python 3.6 and higher.

You could add `importlib_metadata ; python_version<"3.8"` to the dependencies in addition to adding a lower bound for the python version.

**Comment by mdomke** [comment]
You're right. The `pyproject.toml` actually misses a `requires-python` statement and only mentions the supported versions in the `classifiers`. I will fix that. Python 3.7 is end-of-life since mid 2023 however and is not supported anymore by this library. We will also drop support for Python 3.8 in the next release of Mongomock.
